version: '3.8'
name: swarch2022ii

services:

  # ---- L1 - Data ----
  db:
    extends:
      file: ./swarch2022ii_db/docker-compose.yml
      service: db

  # ---- L2 - Logic, Part 1 ----
  ms:
    extends:
      file: ./swarch2022ii_ms/docker-compose.yml
      service: ms

  # ---- L3 - Logic, Part 2 ----
  ag:
    extends:
      file: ./swarch2022ii_ag/docker-compose.yml
      service: ag

  # ---- L4 - Presentation ----

  # ---- L5 - Security ----
  ldap:
    extends:
      file: ./swarch2022ii_ldap/docker-compose.yml
      service: ldap

  proxy:
    extends:
      file: ./swarch2022ii_proxy/docker-compose.yml
      service: proxy

  # ---- L6 - Interoperability ----
  sa_user_ss_db:
    extends:
      file: ./sa_user_ss/docker-compose.yml
      service: sa_user_ss_db

  sa_user_ss:
    extends:
      file: ./sa_user_ss/docker-compose.yml
      service: sa_user_ss

  sa_bank_ss_db:
    extends:
      file: ./sa_bank_ss/docker-compose.yml
      service: sa_bank_ss_db

  sa_bank_ss:
    extends:
      file: ./sa_bank_ss/docker-compose.yml
      service: sa_bank_ss

volumes:
  db_data:

  ldap_data:
  ldap_config:
  ldap_certs:

  sa_user_ss_db_data:
  sa_bank_ss_db_data:
