version: '3.8'
name: swarch2022ii

services:

  # ---- L1 - Data ----
  db:
    extends:
      file: ./swarch2022ii_db/docker-compose.yml
      service: db

  db_client:
    extends:
      file: ./swarch2022ii_db/docker-compose.yml
      service: db_client

  # ---- L2 - Logic, Part 1 ----
  ms:
    extends:
      file: ./swarch2022ii_ms/docker-compose.yml
      service: ms

  # ---- L3 - Logic, Part 2 ----
  ag:
    extends:
      file: ./swarch2022ii_ag/docker-compose.yml
      service: ag

  # ---- L4 - Presentation ----

  # ---- L5 - Security ----
  ldap:
    extends:
      file: ./swarch2022ii_ldap/docker-compose.yml
      service: ldap

  phpldapadmin:
    extends:
      file: ./swarch2022ii_ldap/docker-compose.yml
      service: phpldapadmin

  proxy:
    extends:
      file: ./swarch2022ii_proxy/docker-compose.yml
      service: proxy

volumes:
  db_data:

  ldap_data:
  ldap_config:
  ldap_certs:
  phpldapadmin_data:
