@baseUrl=http://localhost:3010/wsusers

### Get the WSDL
GET {{baseUrl}}/wsdl HTTP/1.1

### checkUser
POST {{baseUrl}}/action HTTP/1.1

<soapenv:Envelope
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:urn="urn:WashOutUser"
>
    <soapenv:Header/>
    <soapenv:Body>
        <urn:checkUser
            soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
        >
            <userId xsi:type="xsd:int">1</userId>
        </urn:checkUser>
    </soapenv:Body>
</soapenv:Envelope>